devmgmt/file_upload/backadmin/urls.py
from django.conf.urls import url
from . import views

app_name = "backadmin"
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^verify/', views.verify, name='verify'),
	url(r'^return_permissions/', views.return_permissions, name="return_permissions"),
	url(r'^user_logout/', views.user_logout, name="user_logout"),
	url(r'^change_ap/', views.change_ap, name="change_ap"),
	url(r'^change_pass/', views.user_changepass, name='user_changepass'),
	url(r'^upgrade/', views.upgrade, name='upgrade'),
	url(r'^upgrade_ext/', views.upgrade_ext, name='upgrade_ext')
]

devmgmt/file_upload/file-upload/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', lambda x: HttpResponseRedirect('backadmin/')),
    url(r'^upload/', include('fileupload.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ssidmod/', include('ssidmod.urls')),
    url(r'^changecaptive/', include('changecaptive.urls')),
    url(r'^changepermissions/', include('changepermissions.urls')),
    url(r'^changevariables/', include('changevars.urls')),
    url(r'^backadmin/', include('backadmin.urls')),
    url(r'^createuser/', include('createuser.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

devmgmt/file_upload/fileupload/urls.py
from django.conf.urls import url
from fileupload.views import (
        #BasicPlusVersionCreateView,
        EkFileCreateView, EkFileDeleteView, EkFileListView,
        )
from . import views

app_name='fileupload'
urlpatterns = [
    url(r'^new/$', EkFileCreateView.as_view(), name='upload-new'),
    url(r'^delete/(?P<pk>\d+)$', EkFileDeleteView.as_view(), name='upload-delete'),
    url(r'^view/$', EkFileListView.as_view(), name='upload-view'),
    url(r'^$',views.index,name='index'),
    url(r'^transfer/$', views.transferx, name="transfer"),
    url(r'^verify_USB/$', views.verify_USB, name="verifyusb"),
    url(r'^user_logout/$', views.user_logout, name='userlogout'),
    url(r'^download_to_USB/$', views.download_to_USBx, name='downloadtousb'),
    url(r'^return_exts/$', views.serve_extensions, name="serve_exts"),
    url(r'^verify_USB2/$', views.verify_USB2, name='get_usb'),
    url(r'^apply_changes/$', views.apply_changes, name='apply_changes'),
]

devmgmt/file_upload/ssidmod/urls.py
from django.conf.urls import url

from . import views

app_name = "ssidmod"
urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^modify_ssid/$', views.modify_ssid, name="modify_ssid"),
	]

devmgmt/file_upload/fileupload/models.py
import os, shutil
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings
from django.core.exceptions import ValidationError
from django.http import HttpResponse,HttpResponseRedirect
from django.core.files.storage import FileSystemStorage
# Create your models here.


def r_file_name(instance, filename):
    filename = filename.encode('utf-8')
    fullname = os.path.join(settings.MEDIA_ROOT, filename)
    if os.path.exists(fullname):
        try:
            old = EkFile.objects.get(file_upload=filename)
            old.delete()
        except:
            pass
    format = filename
    return format

allowed_exts = settings.ACCEPTED_EXTNS

def validate_file_extension(value):
  ext = os.path.splitext(value.name)[1]
  #valid_extensions = ['.pdf','.doc','.docx']
  if not ext in tuple(allowed_exts):
      raise ValidationError(u'File not supported!')

content_root = settings.CONTENT_ROOT

class EkFile(models.Model):
    file_upload = models.FileField(max_length=250, upload_to=r_file_name, validators=[validate_file_extension])
    slug = models.SlugField(max_length=250, blank=True)
    type_of_file=models.CharField(max_length=50,blank=True)
    path_of_file=models.CharField(max_length=250,blank=True)
    def __str__(self):
        return self.file_upload.name+","+self.type_of_file+","+self.path_of_file+","+self.slug
       #return file_n+","+self.file_upload.name+","+self.type_of_file+","+self.path_of_file

    def save(self, *args, **kwargs):
        self.slug = self.file_upload.name
        index=self.slug.rfind('.')
        self.type_of_file = self.slug[index+1:]
        self.path_of_file = self.file_upload.path
        super(EkFile, self).save(*args, **kwargs)
        shutil.move(content_root+self.file_upload.name,self.path_of_file)
        os.chmod(self.path_of_file, 0644)
        EkFile.objects.filter(file_upload=self.file_upload.name).update(file_upload=self.slug)

    def delete(self, *args, **kwargs):
        """delete -- Remove to leave file."""
        self.file_upload.delete(False)
        super(EkFile, self).delete(*args, **kwargs)


class Content(models.Model):
        ekfile=models.ForeignKey(EkFile,on_delete=models.CASCADE)
        filename=models.CharField(max_length=250)

        def __str__(self):
                return self.filename

        def save(self,*args,**kwargs):
                super(Content,self).save(*args,**kwargs)

        def delete(self,*args,**kwargs):
                super(Content,self).delete(*args,**kwargs)


class Permission(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	down_to_usb = models.BooleanField(default=False)
	up_from_usb = models.BooleanField(default=False)
	up_from_dev = models.BooleanField(default=True)
	delete_files = models.BooleanField(default=False)
	ssid_mod = models.BooleanField(default=False)
	captive_mod = models.BooleanField(default=False)
	global_vars_mod = models.BooleanField(default=False)

	def __str__(self):
		return 'Permissions for ' + str(self.user)

	def get_permissions(self):
		perms_dict = {'down_to_usb' : self.down_to_usb,
					  'up_from_usb' : self.up_from_usb,
					  'up_from_dev' : self.up_from_dev,
					  'ssid_mod' : self.ssid_mod,
					  'delete_files' : self.delete_files,
					  'captive_mod' : self.captive_mod,
					  'global_vars_mod' : self.global_vars_mod}
		return perms_dict

@receiver(post_save, sender=User)
def create_permissions (sender, instance, created, **kwargs):
	if created:
		Permission.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_permissions (sender, instance, **kwargs):
	if instance.is_superuser:
		instance.permission.down_to_usb = True
		instance.permission.up_from_usb = True
		instance.permission.up_from_dev = True
		instance.permission.ssid_mod = True
		instance.permission.captive_mod = True
		instance.permission.global_vars_mod = True
		instance.permission.save()

devmgmt/file_upload/fileupload/views.py
# -*- coding: utf-8 -*-
import json, os, subprocess, getpass, shutil, sys
import logging
from .USBFinder import attemptMount,transfer_file, get_usb_name
from hashlib import sha1
from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import ensure_csrf_cookie
from django.template import Context, loader
from django.shortcuts import render,get_object_or_404
from django.views.generic import CreateView, DeleteView, ListView
from .models import EkFile, Content
from django.contrib.auth.models import User
from .response import JSONResponse, response_mimetype
from .serialize import serialize
from django.urls import reverse
from .extract import extractit
from .deleteExtract import deleteit
from distutils.dir_util import copy_tree
from django.conf import settings
from django.contrib.auth.decorators import login_required

reload(sys)
sys.setdefaultencoding('utf-8')

staticFileLocRoot = None

old_files = []
filesx = []
total_amount = 0
total_done = 0
count = 0
is_auth = True
optional_flag = False
percentage_done = 0
perm_dict = None
user = None
telemetry = None
local_files = []
allowed_exts = settings.ACCEPTED_EXTNS
message = ''
first_msg = ''

class User_Permissions:
    def __init__(self, user):
        self.permissions = user.permission.get_permissions()

    def get_permissions(self):
        return self.permissions

class NoFilesError(ValueError):
    def __init__ (self, arg = None):
        self.strerror = arg
        self.args = {arg}

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('../../upload/')

@login_required(login_url="/backadmin/")
def index(request):
    return render(request,'fileupload/LOGIN.html')

def verify(request, optional=False):
    flag='INIT'
    global optional_flag
    optional_flag = False
    global is_auth, user, password, telemetry
    if optional:
        optional_flag = True
        return HttpResponseRedirect('../new')
    try:
        user=User.objects.get(username=request.POST['email'])
        logger = logging.getLogger(__name__)
        password=request.POST.get('password', '')
    #_,salt,hashpw=user.password.split('$')
        logger.error(request.POST.get('email', '')+","+request.POST.get('password', '')+" \n")
        logger.error(user.password+", username is "+user.username)
        flag='REAL'
    except User.DoesNotExist:
        flag = 'FAKE'
    if(flag == 'REAL' and user.check_password(password)):
        global perm_dict
        perm_dict = User_Permissions(user)
        is_auth = True
        ############################################################
        # Load values from profile.json file                       #
        ############################################################
        staticFileLocRoot = settings.MEDIA_ROOT
        telemetry = settings.TELEMETRY

        return HttpResponseRedirect('new/')
    else:
        return render(request,'fileupload/LOGIN.html',{'invalid':'not a valid username or password',})

#=======
config_json_dir = settings.CONFIG_JSON_DIR
config_json_name = settings.CONFIG_JSON_NAME

class EkFileCreateView(CreateView):
    model = EkFile
    fields = "__all__"

    def form_valid(self, form):
        self.object = form.save()
        print "self Object: "
        print unicode(self.object)
        self.object.file_upload = self.object.slug

        # Checking for duplicate files and deleting them

        all_files = EkFile.objects.filter(file_upload = self.object.file_upload)
        if len(all_files) > 1:
            for thing in all_files:
                if thing is not self.object:
                    del(thing)

        files = [serialize(self.object)]
        global first_msg
        first_msg = 'Successful!'
        data = {'files': files}
        print 'Before you send post request'
        print self.object.path_of_file
        print '-'*10 + 'EXTRACT' + '-'*10
        
        if(self.object.path_of_file.endswith(".json")):
            if not os.path.exists(config_json_dir):
                os.makedirs(config_json_dir)
            if(self.object.file_upload == config_json_name):
                os.system("service apiserver restart")
            shutil.copy2(self.object.path_of_file, config_json_dir)
            config_db_entry = EkFile.objects.get(file_upload=self.object.file_upload)
            config_db_entry.delete()
        else:
            if(settings.ACTIVE_PROFILE == "ekstep"):
                try:
                    files = extractit(self.object.path_of_file)
                    for f in files:
                        obj=Content(ekfile=self.object,filename=f)
                        obj.save()
                except:
                    print 'Probablemente Dios yo pardone.'
                    first_msg = 'Corrupt ecar file!'
                    self.object.delete()
        data['msg'] = first_msg
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        print str(response)
        return response

    def form_invalid(self, form):
        data = json.dumps(form.errors)
	print data + ' omg fail '
        return HttpResponse(content=data, status=400, content_type='application/json')




class EkFileDeleteView(DeleteView):
    model = EkFile

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        print 'Attempting to delete ' + unicode(self.object)
        if(self.object.path_of_file.endswith(".json")):
            json_file = unicode(self.object.file_upload)
            if(json_file == config_json_name):
                return HttpResponseRedirect('/upload/new/')
            file_name = config_json_dir+json_file
            os.remove(file_name)
        else:
            if(settings.ACTIVE_PROFILE == "ekstep"):
                files = Content.objects.filter(ekfile = self.object.id)
                filename = []
                for f in files:
                    filename.append(f.filename)
                    f.delete()
                deleteit(filename)
        self.object.delete()
        response = JSONResponse(True, mimetype=response_mimetype(request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response


class EkFileListView(ListView):
    model = EkFile

    def render_to_response(self, context, **response_kwargs):
        files = [ serialize(p) for p in self.get_queryset() ]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response

def apply_changes(request):
    os.system("service apiserver restart")
    return JsonResponse({'msg': 'Success'})

def verify_USB2(request):
    value = get_usb_name()
    if value is None:
        value = 'null'
    return JsonResponse({'value':value})

def verify_USB(request):
    value = attemptMount()
    response_data = 'disabled'
    if value is not None:
        global filesx
        del(filesx)
        filesx = value
        if len(filesx) > 0:
            response_data = 'active '
    return JsonResponse({'data':response_data})

def serve_extensions(requests):
    global allowed_exts
    return JSONResponse({"exts":allowed_exts})

def download_to_USBx(request):
    print 'Hooray I have been called'
    usb_name = get_usb_name()
    remount = "mount -o remount, rw "+usb_name
    os.system(remount)
    if usb_name is not None:
        local_files_dir = settings.TELEMETRY
	print local_files_dir
        #local_files = []
        #for root, folders, files in os.walk(local_files_dir):
        #    for file in files:
        #        if (not os.path.isdir(file)):
        #            local_files.append(os.path.join(root, file))
	#print local_files
        #actual_index = local_files[0].split('/').index(local_files_dir.split('/')[-2:-1][0]) + 1
        #for file in local_files:
        #    os.chdir(usb_name)
        #    split_list = file.split('/')
        #    for i in range (actual_index, len(split_list) - 1):
        #        if not os.path.exists(split_list[i]):
        #            os.makedirs(split_list[i])
        #        os.chdir(split_list[i])
        command = "cp -r "+ local_files_dir+" "+usb_name
        t = subprocess.Popen(command, shell=True)
        t.communicate()[0]
        os.system("/bin/sync") # one for my master
        os.system("/bin/sync") # one for my'dam
        os.system("/bin/sync") #  and one for the li'l boy who lives down the lane
        romount = "/bin/mount -o remount,ro " + usb_name
        os.system(romount)
        time.sleep(1)  ## And additional saftey..
        result = t.returncode
        if result != 0:
            return JsonResponse ({'res': 'Copy aborted! [USB Unplugged/Insufficient Space?]'})
        return JsonResponse({'res': 'Copy successful'})

    romount = "/bin/mount -o remount,ro " + usb_name
    os.system(romount)
    return JsonResponse({'res':'Reinsert USB'})

def split_dirs(text): #Splits the entire path to get the file name
    splitty = text.split('/')
    value = splitty[len(splitty) - 1]
    return value

def transferx(request):
    print 'Thank you for calling me'
    global filesx
    result = 'ok'
    for subject_file in filesx:
        name = split_dirs(subject_file)
        subject_model = EkFile(file_upload = str(name))
        try:
            z = EkFile.objects.get(file_upload = str(name))
            z.delete()
        except:
            pass
        returncode = transfer_file(subject_file)
        if returncode != 0:
            result = 'notok'
            break
        subject_model.save()
        if name.endswith(".json"):
            if not os.path.exists(config_json_dir):
                os.makedirs(config_json_dir)
                if(name == config_json_name):
                    os.system("service apiserver restart")

devmgmt/file_upload/fileupload/templates/fileupload/LOGIN.html
<!DOCTYPE HTML>
<html>
<head>
<title>File Upload Login</title>
<link rel="stylesheet" href="../static/css/login.css">
</head>
<body>
<div class="login-page">
    <form  class="form" action="{% url 'fileupload:verify' %}" method="post">
    {%csrf_token%}
     {% if invalid %}
           <p>{{invalid}}</p>
     {% endif %}
      <input type="text" id="email" name="email" placeholder="username">
      <br>
      <input type="password" id="password" name="password" placeholder="password">
      <br>
      <button type="submit">Login</button>
      <div class="container">
        <img src="/static/logo.png" alt="logo"/>
      </div>
    </form>
</div>
</body>
</html>

devmgmt/file_upload/fileupload/templates/fileupload/downloadFiles.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Transfer USB Data</title>
<!-- All scripts go below this! -->
		<link rel="stylesheet" href="/static/css/bootstrap.min.css">
		<script src="/static/js/jquery-3.2.1.min.js" type="application/javascript"></script>
<!-- All scripts are above this! -->
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<body>
		<div class="container-fluid" align="center">
			<h1>USB File Transfer</h1>
		
		<div class="jumbotron">
			{% if files_existing %}
				<div class = "progress">
							<div class = "progress-bar progress-bar-striped active" role="progressbar" aria-valuenow = "{{ percentage_done }}" aria-valuemin = "0" aria-valuemax="100"
									style = "width:{{ percentage_done }}%">{{ percentage_done }}%
							</div>
						</div>
				<!-- Code to open a box and get the files here -->
				<p>Files being downloaded:
					{% for file in files_existing %}
						<p><b>{{ file.file_upload }}</b><!-- {{ file.file_desc }} --></p><br/>
					{% endfor  %}
				<form action='../return_USB/' method="post" name="InitUSB">
				{% csrf_token %}
					<!--input type="submit" value="Download Files" class = "btn btn-info {{ btn_check_flag }}" align="center"-->
					{% if show_output %}
					<!--{% for file in files_existing %} -->
					<form action='../transfer/' method="post" name="TransferFiles">
					{% csrf_token %}

						
							<input type="hidden" value="{{ current_count }}" name="file_descriptor">
							<p><script tyoe="application/javascript">
								document.TransferFiles.submit();
							</script></p>
						

					</form>
					<!--{% endfor %}-->
					{% endif %}
				</form>
				{% if download_more %}
						{% else %}
							<p>All Files have been transferred to the Raspberry Pi</p>
						{% endif %}
			{% else %}
				<!-- Code to tell the user to come back later here -->
				<p algin="center">No new files are available through the USB. Insert new USB and refresh.<p>
			{% endif %}
		</div>
		</div>
	</body>
</html>

devmgmt/file_upload/fileupload/templates/fileupload/ekfile_form.html
{% extends "backadmin_base.html" %}
{% load upload_tags %}

{% block content %}
<input type="hidden" id="refresh" value="no">
<div class="container">
    <h1 id="h">File Upload    <img src='/static/img/loading.gif' id="loading_chakra" alt = "uploading..." height="30px" width="30px"/></h1><br/>
    <div class="input-group">
    	<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
    	<input id="search" type="text" class="form-control" placeholder="Search for files..." />
    </div><hr />
    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" method="post" action="." enctype="multipart/form-data">{% csrf_token %}

        <div class="row fileupload-buttonbar">
            <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button" id="dev_up" hidden="true" style="display:none;" onclick='activate()'>
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                </span>
                <input type="file" name="file_upload" multiple id="file_in" style='display:none;'/>
                <span>
                  <button type="button" class="btn btn-danger delete" id="delete_all" style="display:none;">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete all</span>
                  </button>
                </span>

                <span data-toggle="tooltip" title="" id="usb_span" data-placement="right" style="display:none;">
                  <button type="button" class="btn btn-primay start" id="usb" onclick="usbUpload()" style="display:none;">
                      <i class="glyphicon glyphicon-upload"></i>
                      <span>USB upload</span>
                    </button>
                </span>

                <button type="button" class="btn btn-primay start" id="usb_down" onClick="telemetry_transfer()" style="display:none;">
                    <i class="glyphicon glyphicon-download"></i>
                    <span>USB download</span>
                </button>

                <button type="button" class="btn btn-primary start" id="apply_changes" style="display:none;">
                    <i class="glyphicon glyphicon-ok"></i>
                    <span>Apply Changes</span>
                </button>

                <!--input type="checkbox" class="toggle"-->
                <!-- The loading indicator is shown during file processing -->
                <span class="fileupload-loading"></span>
            </div>
            <!-- The global progress information -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress information -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files" id="files_table"></tbody></table>
    </form>
    <br>

</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
{% upload_js %}


<!--script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script-->
<script src="/static/js/ajax-utils.js"></script>
<script src="/static/js/scripts.js"></script>

<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/static/js/vendor/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="/static/js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="/static/js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="/static/js/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
 <script src="/static/js/bootstrap.min.js"></script>
<!-- blueimp Gallery script -->
<script src="/static/js/jquery.blueimp-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/static/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/static/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/static/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/static/js/jquery.fileupload-image.js"></script>
<!-- The File Upload audio preview plugin -->
<script src="/static/js/jquery.fileupload-audio.js"></script>
<!-- The File Upload video preview plugin -->
<script src="/static/js/jquery.fileupload-video.js"></script>
<!-- The File Upload validation plugin -->
<script src="/static/js/jquery.fileupload-validate.js"></script>
<!-- The File Upload user interface plugin -->
<script src="/static/js/jquery.fileupload-ui.js"></script>
<!-- The main application script -->
<script src="/static/js/main.js"></script>
<script src="/static/js/locale.js"></script>
<script src="/static/js/csrf.js"></script>
<script>
$(function() {
    $("#telemetry_progress").hide();
    $("#loading_chakra").hide();
    $.getJSON('../verify_USB/', function (response) {
            var obj = JSON.parse(JSON.stringify(response));
            document.getElementById("usb").setAttribute("class", "btn btn-primay start " + obj.data);
            if (obj.data == 'disabled') {
            	document.getElementById("usb_span").setAttribute("title", "Please insert USB device and refresh");
              document.getElementById("usb").setAttribute("onclick", "javascript:void(0);");
            	$('[data-toggle="tooltip"]').tooltip();
            }
        });
    $.getJSON('../verify_USB2/', function(response) {
      var obj = JSON.parse(JSON.stringify(response));
      if (obj['value'] == 'null') {
        console.log(obj['value']);
        document.getElementById("usb_down").setAttribute("class", "btn btn-primay start disabled");
        document.getElementById("usb_down").setAttribute("onclick", "javascript:void(0);");
      }
    })
    $.getJSON('../return_exts/', function(response) {
        var ob = JSON.parse(JSON.stringify(response));
        var exts = ob['exts'];
       // alert(exts);
        var extstring = '';
        for (var i = 0; i < exts.length; i++) {
            extstring = extstring.concat(', ', exts[i]);
        }
        extstring = extstring.substring(2, extstring.length);
        document.getElementById("file_in").setAttribute("accept", extstring);

    });
    $("#search").keyup(function() {
    	var searchString = $("#search").val();
    	filter_table(searchString.toLowerCase());
    });
});

function telemetry_transfer() {
  $('#loading_chakra').show();
  $.getJSON('/upload/download_to_USB', function (response) {
    var ob = JSON.parse(JSON.stringify(response));
    alert(ob['res']);
  $('#loading_chakra').hide();
  });
}

function usbUpload() {
  $('#loading_chakra').show();
  $.getJSON('/upload/transfer', function(response) {
    var ob = JSON.parse(JSON.stringify(response));
    switch(ob['result']) {
      case 'ok' : alert('Successful!');
                  break;
      case 'notok' : alert('Transfer failure!');
                     break;
      case 'notok2' : alert("Corrupt ecar file encountered!");
                      break;
      default: alert('Unexpected error occured!');
    }
    window.location.reload();
  });
}

function activate() {
  $('#file_in').focus().trigger('click');
}
$('#apply_changes').click(function() {
  $.getJSON('/upload/apply_changes', function(response) {
    var ob = JSON.parse(JSON.stringify(response));
    alert(ob['msg']);
  });
});
/*
function telemetry_transferx() {
    var loop = true;
    $('#telemetry_form').submit({
        url : '/upload/download_to_USB/',
        type : "POST",
        method : "POST",
        datatype : 'json',
        data : {'val':'INIT'},
        success : function(resp) {
            $("#progress_outer").show();
            var z = JSON.parse(JSON.stringify(resp));
            var fileLength = parseInt(z.length);
            var i = 0;
            var current = parseInt(z.value) + 1;
            var maximum = parseInt(z.length);
            for (; i < fileLength; i++) {
                document.getElementById("counter").setAttribute("value", current);
                var percent = current/maximum*100;
                var pbar = document.getElementById("progress_inner");
                pbar.setAttribute("style", "width:"+percent.toString()+"%");
                pbar.innerHTML = percent.toString()+"%";
                $('#telemetry_form').submit({
                    url : 'download_to_USB/',
                    datatype : 'json',
                    type : "POST",
                    method : "POST",
                    data : {'val' : document.getElementById("counter").getAttribute("value")},
                    success : function(resp) {
                        z = JSON.parse(JSON.stringify(resp));
                        if (z.value == null) {
                            //document.getElementById("usb_text").innerHTML = z.res;
                            loop = false;
                            return;
                        }
                        else {
                            current = parseInt(z.value);
                        }
                    }
                });
                if (!(loop)) {
                    $("#progress_outer").hide();
                    return;
                }
            }
        }
    });

}
*/
function filter_table(string) {
  var table = document.getElementById("files_table");
  if (table != null) {
    file_rows = table.childNodes;
    for (var i = 0; i < file_rows.length; i++) {
      var row = file_rows[i];
      name = row.getAttribute('id').toLowerCase();
      if (name.substring(name.lastIndexOf('/'), name.length).search(string) != -1) {
        $(row).show();
      }
      else {
        $(row).hide();
      }
    }
  }
}
</script>

{% endblock %}