devmgmt/file_upload/backadmin/urls.py
from django.conf.urls import url
from . import views

app_name = "backadmin"
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^verify/', views.verify, name='verify'),
	url(r'^return_permissions/', views.return_permissions, name="return_permissions"),
	url(r'^user_logout/', views.user_logout, name="user_logout"),
	url(r'^change_ap/', views.change_ap, name="change_ap"),
	url(r'^change_pass/', views.user_changepass, name='user_changepass'),
	url(r'^upgrade/', views.upgrade, name='upgrade'),
	url(r'^upgrade_ext/', views.upgrade_ext, name='upgrade_ext')
]

devmgmt/file_upload/changecaptive/urls.py
from django.conf.urls import url

from . import views

app_name = "changecaptive"
urlpatterns = [
	url (r'^$', views.index, name='index'),
	url (r'^change_data/$', views.change_data, name='changedata'),
	url (r'^change_logo/$', views.change_logo, name='changelogo'),
	url (r'^change_apk/$', views.change_apk, name='changeapk'),
	#url (r'^captive_display/$', views.captive_display, name='captivedisplay'),
	url (r'^return_text/$', views.return_text, name="returntext")
]

devmgmt/file_upload/changevars/urls.py
from django.conf.urls import url
from . import views

app_name = 'changevars'
urlpatterns = [
	url(r'^$', views.load_page, name="loadpage"),
	url(r'^update_data/', views.update_data, name="update_data"),
	]

devmgmt/file_upload/createuser/urls.py
from django.conf.urls import url
from . import views

app_name='createuser'

urlpatterns = [
	url(r'^new/$', views.index, name="index"),
	url(r'^delete_user/$', views.delete_user, name="delete_user"),
	url(r'^delete/', views.delete, name="delete"),
]

devmgmt/file_upload/file-upload/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', lambda x: HttpResponseRedirect('backadmin/')),
    url(r'^upload/', include('fileupload.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ssidmod/', include('ssidmod.urls')),
    url(r'^changecaptive/', include('changecaptive.urls')),
    url(r'^changepermissions/', include('changepermissions.urls')),
    url(r'^changevariables/', include('changevars.urls')),
    url(r'^backadmin/', include('backadmin.urls')),
    url(r'^createuser/', include('createuser.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

devmgmt/file_upload/fileupload/urls.py
from django.conf.urls import url
from fileupload.views import (
        #BasicPlusVersionCreateView,
        EkFileCreateView, EkFileDeleteView, EkFileListView,
        )
from . import views

app_name='fileupload'
urlpatterns = [
    url(r'^new/$', EkFileCreateView.as_view(), name='upload-new'),
    url(r'^delete/(?P<pk>\d+)$', EkFileDeleteView.as_view(), name='upload-delete'),
    url(r'^view/$', EkFileListView.as_view(), name='upload-view'),
    url(r'^$',views.index,name='index'),
    url(r'^transfer/$', views.transferx, name="transfer"),
    url(r'^verify_USB/$', views.verify_USB, name="verifyusb"),
    url(r'^user_logout/$', views.user_logout, name='userlogout'),
    url(r'^download_to_USB/$', views.download_to_USBx, name='downloadtousb'),
    url(r'^return_exts/$', views.serve_extensions, name="serve_exts"),
    url(r'^verify_USB2/$', views.verify_USB2, name='get_usb'),
    url(r'^apply_changes/$', views.apply_changes, name='apply_changes'),
]

devmgmt/file_upload/ssidmod/urls.py
from django.conf.urls import url

from . import views

app_name = "ssidmod"
urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^modify_ssid/$', views.modify_ssid, name="modify_ssid"),
	]

devmgmt/file_upload/fileupload/models.py
import os, shutil
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings
from django.core.exceptions import ValidationError
from django.http import HttpResponse,HttpResponseRedirect
from django.core.files.storage import FileSystemStorage
# Create your models here.


def r_file_name(instance, filename):
    filename = filename.encode('utf-8')
    fullname = os.path.join(settings.MEDIA_ROOT, filename)
    if os.path.exists(fullname):
        try:
            old = EkFile.objects.get(file_upload=filename)
            old.delete()
        except:
            pass
    format = filename
    return format

allowed_exts = settings.ACCEPTED_EXTNS

def validate_file_extension(value):
  ext = os.path.splitext(value.name)[1]
  #valid_extensions = ['.pdf','.doc','.docx']
  if not ext in tuple(allowed_exts):
      raise ValidationError(u'File not supported!')

content_root = settings.CONTENT_ROOT

class EkFile(models.Model):
    file_upload = models.FileField(max_length=250, upload_to=r_file_name, validators=[validate_file_extension])
    slug = models.SlugField(max_length=250, blank=True)
    type_of_file=models.CharField(max_length=50,blank=True)
    path_of_file=models.CharField(max_length=250,blank=True)
    def __str__(self):
        return self.file_upload.name+","+self.type_of_file+","+self.path_of_file+","+self.slug
       #return file_n+","+self.file_upload.name+","+self.type_of_file+","+self.path_of_file

    def save(self, *args, **kwargs):
        self.slug = self.file_upload.name
        index=self.slug.rfind('.')
        self.type_of_file = self.slug[index+1:]
        self.path_of_file = self.file_upload.path
        super(EkFile, self).save(*args, **kwargs)
        shutil.move(content_root+self.file_upload.name,self.path_of_file)
        os.chmod(self.path_of_file, 0644)
        EkFile.objects.filter(file_upload=self.file_upload.name).update(file_upload=self.slug)

    def delete(self, *args, **kwargs):
        """delete -- Remove to leave file."""
        self.file_upload.delete(False)
        super(EkFile, self).delete(*args, **kwargs)


class Content(models.Model):
        ekfile=models.ForeignKey(EkFile,on_delete=models.CASCADE)
        filename=models.CharField(max_length=250)

        def __str__(self):
                return self.filename

        def save(self,*args,**kwargs):
                super(Content,self).save(*args,**kwargs)

        def delete(self,*args,**kwargs):
                super(Content,self).delete(*args,**kwargs)


class Permission(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	down_to_usb = models.BooleanField(default=False)
	up_from_usb = models.BooleanField(default=False)
	up_from_dev = models.BooleanField(default=True)
	delete_files = models.BooleanField(default=False)
	ssid_mod = models.BooleanField(default=False)
	captive_mod = models.BooleanField(default=False)
	global_vars_mod = models.BooleanField(default=False)

	def __str__(self):
		return 'Permissions for ' + str(self.user)

	def get_permissions(self):
		perms_dict = {'down_to_usb' : self.down_to_usb,
					  'up_from_usb' : self.up_from_usb,
					  'up_from_dev' : self.up_from_dev,
					  'ssid_mod' : self.ssid_mod,
					  'delete_files' : self.delete_files,
					  'captive_mod' : self.captive_mod,
					  'global_vars_mod' : self.global_vars_mod}
		return perms_dict

@receiver(post_save, sender=User)
def create_permissions (sender, instance, created, **kwargs):
	if created:
		Permission.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_permissions (sender, instance, **kwargs):
	if instance.is_superuser:
		instance.permission.down_to_usb = True
		instance.permission.up_from_usb = True
		instance.permission.up_from_dev = True
		instance.permission.ssid_mod = True
		instance.permission.captive_mod = True
		instance.permission.global_vars_mod = True
		instance.permission.save()

devmgmt/file_upload/fileupload/views.py
# -*- coding: utf-8 -*-
import json, os, subprocess, getpass, shutil, sys
import logging
from .USBFinder import attemptMount,transfer_file, get_usb_name
from hashlib import sha1
from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import ensure_csrf_cookie
from django.template import Context, loader
from django.shortcuts import render,get_object_or_404
from django.views.generic import CreateView, DeleteView, ListView
from .models import EkFile, Content
from django.contrib.auth.models import User
from .response import JSONResponse, response_mimetype
from .serialize import serialize
from django.urls import reverse
from .extract import extractit
from .deleteExtract import deleteit
from distutils.dir_util import copy_tree
from django.conf import settings
from django.contrib.auth.decorators import login_required

reload(sys)
sys.setdefaultencoding('utf-8')

staticFileLocRoot = None

old_files = []
filesx = []
total_amount = 0
total_done = 0
count = 0
is_auth = True
optional_flag = False
percentage_done = 0
perm_dict = None
user = None
telemetry = None
local_files = []
allowed_exts = settings.ACCEPTED_EXTNS
message = ''
first_msg = ''

class User_Permissions:
    def __init__(self, user):
        self.permissions = user.permission.get_permissions()

    def get_permissions(self):
        return self.permissions

class NoFilesError(ValueError):
    def __init__ (self, arg = None):
        self.strerror = arg
        self.args = {arg}

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('../../upload/')

@login_required(login_url="/backadmin/")
def index(request):
    return render(request,'fileupload/LOGIN.html')

def verify(request, optional=False):
    flag='INIT'
    global optional_flag
    optional_flag = False
    global is_auth, user, password, telemetry
    if optional:
        optional_flag = True
        return HttpResponseRedirect('../new')
    try:
        user=User.objects.get(username=request.POST['email'])
        logger = logging.getLogger(__name__)
        password=request.POST.get('password', '')
    #_,salt,hashpw=user.password.split('$')
        logger.error(request.POST.get('email', '')+","+request.POST.get('password', '')+" \n")
        logger.error(user.password+", username is "+user.username)
        flag='REAL'
    except User.DoesNotExist:
        flag = 'FAKE'
    if(flag == 'REAL' and user.check_password(password)):
        global perm_dict
        perm_dict = User_Permissions(user)
        is_auth = True
        ############################################################
        # Load values from profile.json file                       #
        ############################################################
        staticFileLocRoot = settings.MEDIA_ROOT
        telemetry = settings.TELEMETRY

        return HttpResponseRedirect('new/')
    else:
        return render(request,'fileupload/LOGIN.html',{'invalid':'not a valid username or password',})

#=======
config_json_dir = settings.CONFIG_JSON_DIR
config_json_name = settings.CONFIG_JSON_NAME

class EkFileCreateView(CreateView):
    model = EkFile
    fields = "__all__"

    def form_valid(self, form):
        self.object = form.save()
        print "self Object: "
        print unicode(self.object)
        self.object.file_upload = self.object.slug

        # Checking for duplicate files and deleting them

        all_files = EkFile.objects.filter(file_upload = self.object.file_upload)
        if len(all_files) > 1:
            for thing in all_files:
                if thing is not self.object:
                    del(thing)

        files = [serialize(self.object)]
        global first_msg
        first_msg = 'Successful!'
        data = {'files': files}
        print 'Before you send post request'
        print self.object.path_of_file
        print '-'*10 + 'EXTRACT' + '-'*10
        
        if(self.object.path_of_file.endswith(".json")):
            if not os.path.exists(config_json_dir):
                os.makedirs(config_json_dir)
            if(self.object.file_upload == config_json_name):
                os.system("service apiserver restart")
            shutil.copy2(self.object.path_of_file, config_json_dir)
            config_db_entry = EkFile.objects.get(file_upload=self.object.file_upload)
            config_db_entry.delete()
        else:
            if(settings.ACTIVE_PROFILE == "ekstep"):
                try:
                    files = extractit(self.object.path_of_file)
                    for f in files:
                        obj=Content(ekfile=self.object,filename=f)
                        obj.save()
                except:
                    print 'Probablemente Dios yo pardone.'
                    first_msg = 'Corrupt ecar file!'
                    self.object.delete()
        data['msg'] = first_msg
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        print str(response)
        return response

    def form_invalid(self, form):
        data = json.dumps(form.errors)
	print data + ' omg fail '
        return HttpResponse(content=data, status=400, content_type='application/json')




class EkFileDeleteView(DeleteView):
    model = EkFile

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        print 'Attempting to delete ' + unicode(self.object)
        if(self.object.path_of_file.endswith(".json")):
            json_file = unicode(self.object.file_upload)
            if(json_file == config_json_name):
                return HttpResponseRedirect('/upload/new/')
            file_name = config_json_dir+json_file
            os.remove(file_name)
        else:
            if(settings.ACTIVE_PROFILE == "ekstep"):
                files = Content.objects.filter(ekfile = self.object.id)
                filename = []
                for f in files:
                    filename.append(f.filename)
                    f.delete()
                deleteit(filename)
        self.object.delete()
        response = JSONResponse(True, mimetype=response_mimetype(request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response


class EkFileListView(ListView):
    model = EkFile

    def render_to_response(self, context, **response_kwargs):
        files = [ serialize(p) for p in self.get_queryset() ]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response

def apply_changes(request):
    os.system("service apiserver restart")
    return JsonResponse({'msg': 'Success'})

def verify_USB2(request):
    value = get_usb_name()
    if value is None:
        value = 'null'
    return JsonResponse({'value':value})

def verify_USB(request):
    value = attemptMount()
    response_data = 'disabled'
    if value is not None:
        global filesx
        del(filesx)
        filesx = value
        if len(filesx) > 0:
            response_data = 'active '
    return JsonResponse({'data':response_data})

def serve_extensions(requests):
    global allowed_exts
    return JSONResponse({"exts":allowed_exts})

def download_to_USBx(request):
    print 'Hooray I have been called'
    usb_name = get_usb_name()
    remount = "mount -o remount, rw "+usb_name
    os.system(remount)
    if usb_name is not None:
        local_files_dir = settings.TELEMETRY
	print local_files_dir
        #local_files = []
        #for root, folders, files in os.walk(local_files_dir):
        #    for file in files:
        #        if (not os.path.isdir(file)):
        #            local_files.append(os.path.join(root, file))
	#print local_files
        #actual_index = local_files[0].split('/').index(local_files_dir.split('/')[-2:-1][0]) + 1
        #for file in local_files:
        #    os.chdir(usb_name)
        #    split_list = file.split('/')
        #    for i in range (actual_index, len(split_list) - 1):
        #        if not os.path.exists(split_list[i]):
        #            os.makedirs(split_list[i])
        #        os.chdir(split_list[i])
        command = "cp -r "+ local_files_dir+" "+usb_name
        t = subprocess.Popen(command, shell=True)
        t.communicate()[0]
        os.system("/bin/sync") # one for my master
        os.system("/bin/sync") # one for my'dam
        os.system("/bin/sync") #  and one for the li'l boy who lives down the lane
        romount = "/bin/mount -o remount,ro " + usb_name
        os.system(romount)
        time.sleep(1)  ## And additional saftey..
        result = t.returncode
        if result != 0:
            return JsonResponse ({'res': 'Copy aborted! [USB Unplugged/Insufficient Space?]'})
        return JsonResponse({'res': 'Copy successful'})

    romount = "/bin/mount -o remount,ro " + usb_name
    os.system(romount)
    return JsonResponse({'res':'Reinsert USB'})

def split_dirs(text): #Splits the entire path to get the file name
    splitty = text.split('/')
    value = splitty[len(splitty) - 1]
    return value

def transferx(request):
    print 'Thank you for calling me'
    global filesx
    result = 'ok'
    for subject_file in filesx:
        name = split_dirs(subject_file)
        subject_model = EkFile(file_upload = str(name))
        try:
            z = EkFile.objects.get(file_upload = str(name))
            z.delete()
        except:
            pass
        returncode = transfer_file(subject_file)
        if returncode != 0:
            result = 'notok'
            break
        subject_model.save()
        if name.endswith(".json"):
            if not os.path.exists(config_json_dir):
                os.makedirs(config_json_dir)
                if(name == config_json_name):
                    os.system("service apiserver restart")

devmgmt/file_upload/fileupload/templates/backadmin_base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Administration</title>
    <!-- JQuery -->
    <script src="/static/js/jquery-3.2.1.min.js"></script>
     <!-- Bootstrap styles -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body style="padding-top: 0px">
<div style="margin-top: 0px">
	<img src="/static/logo.png" alt="logo"/>
</div>
<nav class = "navbar navbar-inverse">
	<ul class = "navbar navbar-nav">
		<li class="dropdown">
			<a class="dropdown-toggle navbar-brand" data-toggle="dropdown" href="javascript:void(0);">
				User: <span id="username"></span>
				<span class = "glyphicon glyphicon-menu-hamburger"></span>
			</a>
			<ul class = "dropdown-menu" id="dropdown">
                <li id = "file_upload" ><a href="{% url 'fileupload:upload-new' %}">File Upload</a></li>
                <li id = "file_upload_bar" class="divider"></li>
                <li id = "ssid_mod" style="display:none;"><a href="{% url 'ssidmod:index' %}">SSID Modification</a></li>
                <li id = "ssid_mod_bar" class="divider" style="display:none;"></li>
                <li id = "captive_mod" style="display:none;"><a href="{% url 'changecaptive:index' %}">Captive Portal Modification</a></li>
                <li id = "captive_mod_bar" class="divider" style="display:none;"></li>
                <li id = "change_vars" style="display:none;"><a href="{% url 'changevars:loadpage' %}">Change Global Variables</a></li>
                <li id = "change_vars_bar" class = "divider" style="display:none;"></li>
                <li id = "user_create" style="display:none;"><a href="{% url 'createuser:index' %}">Superuser Tasks</a></li>
                <li id = "user_create_bar" class="divider" style="display:none;"></li>
                <li id = "change_pass"><a href = "{% url 'backadmin:user_changepass' %}">Change password</a></li>
			</ul>
		</li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
        <li><a href="javascript:void(0);" data-toggle="modal" data-target="#extURLModal">Upgrade</a>
        </li>
		<li style="padding-right:10px"><a href="{% url 'backadmin:user_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
	</ul>

</nav>
<div class = "container">
{% block content %}
    <h1>No content set</h1>
{% endblock %}
</div>
<!-- Modal -->
<div id="extURLModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Enter URL</h4>
      </div>
      <div class="modal-body">
        <p>Paste the URL of the .tgz file!</p>
        <input class="form-control" type="text" id="url_text" />
      </div>
      <div class="modal-footer">
      	<button type="button" class="btn btn-default" data-dismiss="modal" onclick="upgrade()">Use local file instead</button>
        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="upgrade_ext()">Upgrade</button>
      </div>
    </div>

  </div>
</div>
</body>
    <meta name="description" content="File Upload widget with multiple file selection, drag&amp;drop support, progress bars, validation and preview images, audio and video for jQuery. Supports cross-domain, chunked and resumable file uploads and client-side image resizing. Works with any server-side platform (PHP, Python, Ruby on Rails, Java, Node.js, Go etc.) that supports standard HTML form file uploads.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Generic page styles -->
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- blueimp Gallery styles -->
    <link rel="stylesheet" href="/static/css/blueimp-gallery.min.css">
    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
    <link rel="stylesheet" href="/static/css/jquery.fileupload-ui.css">
    <!-- CSS adjustments for browsers with JavaScript disabled -->
    <script>
    $.ajaxSetup({
     beforeSend: function(xhr, settings) {
         function getCookie(name) {
             var cookieValue = null;
             if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                     var cookie = jQuery.trim(cookies[i]);
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) == (name + '=')) {
                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return cookieValue;
         }
         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
             // Only send the token to relative URLs i.e. locally.
             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
         }
     }
});
    $(function() {
    	$.getJSON("{% url 'backadmin:return_permissions' %}", function(response) {
        	var obj = JSON.parse(JSON.stringify(response));
            if (obj.user_name == '_null_') {
                window.location.href = "/backadmin/";
            }
            document.getElementById("username").innerHTML = obj.user_name;
        	if (obj.down_to_usb) {
        		var x = document.getElementById("usb_down");
        		if (x != null) {
            		x.style.display="table-cell";
            	}
        	}
        	if (obj.up_from_usb) {
        		var x = document.getElementById("usb");
        		if (x != null) {
            		x.style.display="inline-table";
                var y = document.getElementById("apply_changes");
                if (y != null) {
                  y.style.display="inline-table";
                }
                var z = document.getElementById("usb_span");
                if (z != null) {
                  z.style.display="inline-table";
                }
            	}
        	}
        	if (obj.up_from_dev) {
        		var x = document.getElementById("dev_up");
        		if (x != null) {
            		x.style.display="inline-table";
            	}
        	}
        	if (obj.delete_files) {
        		var x = document.getElementById("delete_all");
        		if (x != null) {
            		x.style.display="inline-table";
            	}
            var y = document.getElementById("files_table");
            if (y != null) {
              t_r = y.getElementsByTagName("tr");
              table_rows = Array.from(t_r);
              for (row in table_rows) {
                cells = table_rows[row].getElementsByTagName("td");
                Array.from(cells).forEach(function(element) {
                  if (element.getAttribute('name') == 'delete_cell') {
                      element.style.display = "inline";
                  }
                });
              }
            }
          }
        	if (obj.ssid_mod) {
        		document.getElementById("ssid_mod_bar").style.display="block";
            	document.getElementById("ssid_mod").style.display="initial";
        	}
        	if (obj.captive_mod) {
        		document.getElementById("captive_mod_bar").style.display="block";
        		document.getElementById("captive_mod").style.display="initial";
        	}
        	if (obj.superuser_tasks) {
        		document.getElementById("user_create_bar").style.display="block";
            document.getElementById("user_create").style.display="initial";
        	}
          if(obj.global_vars_mod) {
            document.getElementById('change_vars_bar').style.display="block";
            document.getElementById('change_vars').style.display="initial";
          }
        });
        var t = window.location.pathname;
        switch(t) {
            case '/upload/new/':
                document.getElementById("file_upload").setAttribute("class", "active");
                break;
             case '/ssidmod/modify_ssid/':
                document.getElementById("ssid_mod").setAttribute("class", "active");
                break;
             case '/changecaptive/':
                document.getElementById("captive_mod").setAttribute("class", "active");
                break;
             case '/changevariables/':
                document.getElementById("change_vars").setAttribute("class", "active");
                break;
             case '/createuser/new/':
                document.getElementById("user_create").setAttribute("class", "active");
                break;
             case '/backadmin/change_pass/':
                document.getElementById("change_pass").setAttribute("class", "active");
                break;
        }

    });
    function upgrade() {
        var t = document.createElement("form");
        t.setAttribute("method", "post");
        t.setAttribute('action', "{% url 'backadmin:upgrade' %}");
        var f = document.createElement("input");
        f.setAttribute("type", "file");
        f.setAttribute("accept", ".tgz");
        f.setAttribute("hidden", "true");
        f.id = "upgrade_select";
        t.appendChild(f);
        f.onchange = function() {
        $.ajax({
            type: 'post',
            url: "{% url 'backadmin:upgrade' %}",
            data: document.getElementById('upgrade_select').files[0],
            processData: false,
            contentType: false,
            success: function(data) {
                alert(JSON.parse(JSON.stringify(data)).msg);
            }
        });
        };
        $("body").append(t);
        t.style.display="None";
        $('#upgrade_select').trigger('click');
        /*
        $.getJSON("{% url 'backadmin:upgrade' %}", function (response) {
            var obj = JSON.parse(JSON.stringify(response));
            alert(obj.msg);
        });*/
    };

    function upgrade_ext() {
        $.ajax({
            type: 'post',
            url: "{% url 'backadmin:upgrade_ext' %}",
            data: document.getElementById("url_text").value,
            processData: false,
            contentType: false,
            success: function(data) {
                alert(JSON.parse(JSON.stringify(data)).msg);
            }
        });
    }
    </script>
    <noscript><link rel="stylesheet" href="/static/css/jquery.fileupload-ui-noscript.css"></noscript>
</html>