devmgmt/file_upload/backadmin/urls.py
from django.conf.urls import url
from . import views

app_name = "backadmin"
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^verify/', views.verify, name='verify'),
	url(r'^return_permissions/', views.return_permissions, name="return_permissions"),
	url(r'^user_logout/', views.user_logout, name="user_logout"),
	url(r'^change_ap/', views.change_ap, name="change_ap"),
	url(r'^change_pass/', views.user_changepass, name='user_changepass'),
	url(r'^upgrade/', views.upgrade, name='upgrade'),
	url(r'^upgrade_ext/', views.upgrade_ext, name='upgrade_ext')
]

devmgmt/file_upload/file-upload/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', lambda x: HttpResponseRedirect('backadmin/')),
    url(r'^upload/', include('fileupload.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ssidmod/', include('ssidmod.urls')),
    url(r'^changecaptive/', include('changecaptive.urls')),
    url(r'^changepermissions/', include('changepermissions.urls')),
    url(r'^changevariables/', include('changevars.urls')),
    url(r'^backadmin/', include('backadmin.urls')),
    url(r'^createuser/', include('createuser.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

devmgmt/file_upload/ssidmod/urls.py
from django.conf.urls import url

from . import views

app_name = "ssidmod"
urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^modify_ssid/$', views.modify_ssid, name="modify_ssid"),
	]

devmgmt/file_upload/backadmin/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

devmgmt/file_upload/backadmin/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import logout, update_session_auth_hash, authenticate, login
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.conf import settings
import subprocess

# Create your views here.
user_str = None
password = None
perm_dict = None
is_auth = False
fail = False
user = None
result = ''

cdn_scripts_dir = settings.CDN_SCRIPTS_DIR

class UserPermissions:
    def __init__(self, user):
        self.permissions = user.permission.get_permissions()

    def get_permissions(self):
        return self.permissions


def index(request):
    context = {}
    global fail
    if fail:
        context = {'invalid' : 'Invalid username and/or password'}
    return render(request, 'backadmin/LOGIN.html', context)

def verify(request):
    flag = 'FAKE'
    global is_auth, user_str, password, perm_dict, user
    try:
        user_str = User.objects.get(username = request.POST.get('email', None))
        password = request.POST.get('password', None)
        flag = 'REAL'
    except User.DoesNotExist:
        pass
    if ((flag == 'REAL') and user_str.check_password(password)):
        perm_dict = UserPermissions(user_str)
        is_auth = True
        user = authenticate(username = user_str.username, password = password)
        if user is None:
            return HttpResponseRedirect('../')
        if user.is_active:
            login(request, user)
        return HttpResponseRedirect('/upload/new/')
    global fail
    fail = True 
    return HttpResponseRedirect('../')

def return_permissions(request):
    global user
    if user is None:
        return JsonResponse({'user_name':'_null_'})
    try:
        perms = perm_dict.get_permissions()
    except:
        pass
    perms['superuser_tasks'] = user_str.is_superuser
    perms['user_name'] = user_str.username
    return JsonResponse(perms)

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('../')

def change_ap(request):
    command = "sh /x.sh"
    proc = subprocess.Popen(command, shell = True)
    proc.communicate()[0]
    return JsonResponse ({'msg' : 'Access point mode has changed successfully! Wait until server restarts!'})

def upgrade(request):
    if request.method == 'POST':
        upgrade_file = '/opt/openCDN_upgrade.tgz'
        with open(upgrade_file, 'wb+') as utg:
            utg.write(request.body)
        command = cdn_scripts_dir + "upgrade.sh" + ' ' + "file://" + upgrade_file
        proc = subprocess.Popen(command, shell = True)
        proc.communicate()[0]
        
        #z = request.GET.get("url", '');
        #print z + "sikthu maga"
    return JsonResponse ({'msg' : 'Upgrade under way!'})

def upgrade_ext(request):
    if request.method == 'POST':
        val = request.body
        print "val =" + val
        command = cdn_scripts_dir + "upgrade.sh" + ' ' + val 
        proc = subprocess.Popen(command, shell=True)
        proc.communicate()[0]
    return JsonResponse ({'msg' : 'Upgrading!'})

def user_changepass(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            #global result
            result = 'Password changed successfully!'
            return HttpResponseRedirect('/backadmin/change_pass')
        else:
            print 'FAIL'
            return HttpResponseRedirect('/backadmin/change_pass')
    else:
        form = PasswordChangeForm(request.user)
        global result
        result_new = result
        result = ''
        return render(request, 'backadmin/change_password.html', {'form': form, 'result' : result_new})

devmgmt/file_upload/backadmin/templates/backadmin/LOGIN.html
<!DOCTYPE HTML>
<html>
<head>
<title>File Upload Login</title>
<link rel="stylesheet" href="../static/css/login.css">
</head>
<body>
<div class="login-page">
  <form  class="form" action="{% url 'backadmin:verify' %}" method="post">
  <div align="CENTER">
    <img src="/static/logo.png" alt="logo"/>
  </div>
    {%csrf_token%}
     {% if invalid %}
           <p>{{invalid}}</p>
     {% endif %}
      <input type="text" id="email" name="email" placeholder="username">
      <br>
      <input type="password" id="password" name="password" placeholder="password">
      <br>
     <Button type="submit">Login</Button>
  </form>
</div>
</body>
</html>

devmgmt/file_upload/backadmin/templates/backadmin/admin_home.html
{% extends "backadmin_base.html" %}

{% block content %}
<div class ="container" align="CENTER">
	<h1>Welcome, {{ user }}</h1>
	<h3>Please click the links in the navbar to perform administration</h3>
</div>
{% endblock %}

devmgmt/file_upload/backadmin/templates/backadmin/change_password.html
{% extends "backadmin_base.html" %}

{% block content %}
	<div class = "container">
		<form method = "POST">
			{% csrf_token %}
			{{ form }}<hr />
			<div align = "CENTER">
				<button class = "btn btn-primary" type="submit">Save changes</button>
			</div>
		</form>
		<p>
			{% if result %}
				<div align="center">{{ result }}</div> 
			{% endif %}
		</p>
	</div>
	 <script src="/static/js/bootstrap.min.js"></script>
{% endblock %}